default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: <%= ENV['CAHCREATOR_DB'] %>

test:
  <<: *default
  database: CAHCreator_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
